name: Install-and-Test

on:
  push:
    branches: [ "CI" ] # Ejecutar este workflow en cada push a la rama 'main'
  pull_request:
    branches: [ "main" ] # Ejecutar este workflow en cada pull request contra la rama 'main'

jobs:
  build_and_test:
    runs-on: ubuntu-latest # Ejecutar este job en un entorno Ubuntu m치s reciente

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Clona el repositorio al entorno de GitHub Actions

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Usa la versi칩n m치s reciente de Python 3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 

      - name: Build Docker image
        run: docker build -t task-cli-test-image . # Construye la imagen Docker para pruebas

      - name: Run Docker container and execute tests
        run: docker run task-cli-test-image python pytest tests/ # Asume que tus pruebas est치n en el directorio 'tests/' y usas pytest

      - name: Run Coverage
        run: |
          docker run task-cli-test-image coverage run -m pytest tests/ 
          docker run task-cli-test-image coverage report 
          